<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'App\\repository\\RoleRepository' => 'get1',
  'subEntry1' => 'get2',
  'App\\db\\Database' => 'get3',
);

    protected function get2()
    {
        return $this->delegateContainer->get('App\\db\\Database');
    }

    protected function get1()
    {
        $object = new App\repository\impl\RoleRepositoryMySQLImpl($this->get2());
        return $object;
    }

    protected function get3()
    {
        $object = new App\db\Database();
        return $object;
    }

}
